server:
  port: 8010
spring:
  application:
    name: config-service
  cloud:
      config:
        server:
          git:
            uri: https://github.com/qfttxq/demo.git
            search-paths: config-repo
            username: qfttxq
            password: qftt08053318
        profile: dev
        label: dev